site_name: REAL Tutor
site_url: https://REALTutor-EducConsulting.github.io/REALTutor/
nav:
  - REAL Tutorについて: about.md
  - 料金体系: pricing.md
  - よくある質問: faq.md
  - ご相談・お申し込み: contact.md

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: deep purple
      accent: purple

markdown_extensions:
  - admonition
  - pymdownx.details

